# Generated by Django 6.1.1 on 2026-09-23 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_role', models.CharField(choices=[('FACULTY_COORDINATOR', 'Faculty Coordinator'), ('EVENT_COORDINATOR', 'Event Coordinator'), ('REGISTRATION', 'Registration Team'), ('ATTENDANCE', 'Attendance Team'), ('TECHNICAL', 'Technical Team'), ('HOSPITALITY', 'Hospitality Team'), ('MEDIA', 'Media Team'), ('VOLUNTEER', 'Volunteer')], max_length=50)),
                ('responsibility', models.TextField(blank=True, help_text='Specific duty or responsibility for this event.')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='events.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_team_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['team_role', 'member__username'],
                'constraints': [models.UniqueConstraint(fields=('event', 'member', 'team_role'), name='unique_event_member_team_role')],
            },
        ),
    ]
