# Generated by Django 6.1.1 on 2026-09-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('CORE_COMMITTEE', 'Core Committee Member'), ('ORGANIZER', 'Organizer'), ('ADMIN', 'Administrator')], default='STUDENT', max_length=20),
        ),
    ]
