# Generated by Django 6.1.1 on 2026-09-24 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventfaq'),
        ('registrations', '0004_eventfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('FIRST', '1st Place'), ('SECOND', '2nd Place'), ('THIRD', '3rd Place')], max_length=20)),
                ('prize', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.event')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='registrations.registration')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('event', 'registration'), name='unique_event_result_participant'), models.UniqueConstraint(fields=('event', 'position'), name='unique_event_result_position')],
            },
        ),
    ]
